export const CATEGORIIES_ACTION_TYPES = {
  LOAD_DATA_REQUEST: "LOAD_DATA_REQUEST",
  LOAD_DATA_SUCCESS: "LOAD_DATA_SUCCESS",
  LOAD_DATA_FAIL: "LOAD_DATA_FAIL",
  ALLOW_ALL_CATEGORIES: "ALLOW_ALL_CATEGORIES",
  BLOCK_ALL_CATEGORIES: "BLOCK_ALL_CATEGORIES",
  SWITCH_CATEGORY_STATUS: "SWITCH_CATEGORY_STATUS"
};

export const UI_ACTION_TYPES = {
  SWITCH_VISIBILITY: "SWITCH_VISIBILITY"
};